spring:
  application:
    name: learn-langchain4j
  profiles:
    active: local
server:
  port: 8888

langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-max
        api-key: ่ง application-local.yml